### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by earldouglas** [earldouglas/xsbt-web-plugin#261]
**TODO:**

* [ ] Close all issues in [the milestone](https://github.com/earldouglas/xsbt-web-plugin/milestones/2.0.0)
* [ ] Merge everything into *master*
* [ ] Update documentation in `docs/`
* [ ] Update documentation in `README.md`
* [ ] Write release notes
* [ ] Tag release
* [ ] Publish to bintray
* [ ] Verify
* [ ] Publish release notes
